export const blogs = [
    {
      id: 1,
      title: "Case Study: Creating an Engaging Promo Video for a Cryptocurrency Startup",
      author: "John Doe",
      readTime: 7,
      date: "Nov 4, 2023",
      image: "/images/desktop-app.png",
      category: "Cryptocurrency",
    },
    {
      id: 2,
      title: "Case Study: Crafting a Compelling Promo Video for a Blockchain Venture",
      author: "John Doe",
      readTime: 7,
      image: "/images/desktop-app.png",
      date: "Nov 4, 2023",
      category: "Blockchain",
    },
    {
      id: 3,
      title: "Case Study: Developing a Dynamic Promo Video for a Digital Currency Company",
      author: "John Doe",
      readTime: 7,
      date: "Nov 4, 2023",
      image: "/images/desktop-app.png",
      category: "Digital Currency",
    },
    {
      id: 4,
      title: "Case Study: Producing an Eye-Catching Promo Video for a Crypto Firm",
      author: "John Doe",
      readTime: 7,
      date: "Nov 4, 2023",
      image: "/images/desktop-app.png",
      category: "Crypto",
    },
    {
      id: 5,
      title: "Case Study: Designing a Striking Promo Video for a Cryptocurrency Business",
      author: "John Doe",
      readTime: 7,
      date: "Nov 4, 2023",
      image: "/images/desktop-app.png",
      category: "Cryptocurrency",
    },
    {
      id: 6,
      title: "Case Study: Executing a Professional Promo Video for a Crypto Enterprise",
      author: "John Doe",
      readTime: 7,
      date: "Nov 4, 2023",
      image: "/images/desktop-app.png",
      category: "Crypto",
    },
    {
      id: 7,
      title: "Case Study: Launching a Captivating Promo Video for a Blockchain Startup",
      author: "John Doe",
      readTime: 7,
      date: "Nov 4, 2023",
      image: "/images/desktop-app.png",
      category: "Blockchain",
    },
    {
      id: 8,
      title: "Case Study: Showcasing a Unique Promo Video for a Cryptocurrency Initiative",
      author: "John Doe",
      readTime: 7,
      date: "Nov 4, 2023",
      image: "/images/desktop-app.png",
      category: "Cryptocurrency",
    },
    {
      id: 9,
      title: "Case Study: Innovating a Promo Video for a New Crypto Project",
      author: "John Doe",
      readTime: 7,
      date: "Nov 4, 2023",
      image: "/images/desktop-app.png",
      category: "Crypto",
    },
    {
      id: 10,
      title: "Case Study: Strategizing a Promo Video for a Cryptocurrency Venture",
      author: "John Doe",
      readTime: 7,
      date: "Nov 4, 2023",
      image: "/images/desktop-app.png",
      category: "Cryptocurrency",
    },
    {
      id: 11,
      title: "Case Study: Tailoring a Promo Video for a Digital Currency Startup",
      author: "John Doe",
      readTime: 7,
      date: "Nov 4, 2023",
      image: "/images/desktop-app.png",
      category: "Digital Currency",
    },
    {
      id: 12,
      title: "Case Study: Finalizing a Promo Video for a Crypto Business",
      author: "John Doe",
      readTime: 7,
      date: "Nov 4, 2023",
      image: "/images/desktop-app.png",
      category: "Crypto",
    },
  ]

  export const RelatedBlog = [
    {
      id: 1,
      title: "Case Study: Creating an Engaging Promo Video for a Cryptocurrency Startup",
      author: "John Doe",
      readTime: 7,
      date: "Nov 4, 2023",
      image: "/images/desktop-app.png",
      category: "Cryptocurrency",
    },
    {
      id: 2,
      title: "Case Study: Crafting a Compelling Promo Video for a Blockchain Venture",
      author: "John Doe",
      readTime: 7,
      image: "/images/desktop-app.png",
      date: "Nov 4, 2023",
      category: "Blockchain",
    },
    {
      id: 3,
      title: "Case Study: Developing a Dynamic Promo Video for a Digital Currency Company",
      author: "John Doe",
      readTime: 7,
      date: "Nov 4, 2023",
      image: "/images/desktop-app.png",
      category: "Digital Currency",
    },

  ]